[platformio]
default_envs = xiao_esp32c3_ble

[env]
platform = espressif32
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.0

[env:xiao_esp32s3_usb]
board = seeed_xiao_esp32s3
build_flags =
    -D CHAINOSCPAD_TARGET_ESP32S3_USB
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0

[env:xiao_esp32s3_ble]
board = seeed_xiao_esp32s3
build_flags =
    -D CHAINOSCPAD_TARGET_ESP32S3_BLE
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}
    h2zero/NimBLE-Arduino @ 2.5.1

[env:xiao_esp32c3_ble]
board = seeed_xiao_esp32c3
build_flags =
    -D CHAINOSCPAD_TARGET_ESP32C3_BLE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}
    h2zero/NimBLE-Arduino @ 2.5.1

[env:xiao_esp32c6_ble]
board = seeed_xiao_esp32c6
build_flags =
    -D CHAINOSCPAD_TARGET_ESP32C6_BLE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}
    h2zero/NimBLE-Arduino @ 2.5.1

[env:xiao_esp32c5_ble]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c5
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags =
    -D CHAINOSCPAD_TARGET_ESP32C5_BLE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.0
    h2zero/NimBLE-Arduino @ 2.5.1
